### PR TITLE
Fix merge comments on pages

### PR DESCRIPTION
**Pull request by jmbarrios**
There were some merge comments on some files. I remove those comments and fix any marge issue

### CODE REVIEW

**Comment by jmbarrios** [comment]
@orchid00  could you review this pull request?

**Comment by orchid00** [comment]
hi @jmbarrios I'm unsure if deleting the whole paragraph is the way to go. 
I'm reaching our to @fmichonneau because he knows about the lesson template.

**Comment by orchid00** [comment]
I think we should only delete the `==` lines

**Comment by jmbarrios** [comment]
@orchid00 Check this https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/

**Pull request merged**
